runtime: python312

instance_class: F4_1G

entrypoint: waitress-serve --port=8080 --call app:create_app

env_variables:
  HF_ACCESS_TOKEN: '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'
  MONGO_URI: "mongodb+srv://tejasurya18:Surya%400901@poc-cluster.plvno.mongodb.net/?retryWrites=true&w=majority&appName=poc-cluster"
  SECRET_KEY: "NLqsGth9u3CaGALBvblDLGEOCx4tOiEh"
  EXPIRATION_MINUES: 60

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto